SistemaQuestoesWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.home.urls')),
    path('turma/', include('apps.turma.urls')),
    path('professor/', include('apps.professor.urls')),
    path('aluno/', include('apps.aluno.urls')),
    path('questao/', include('apps.questao.urls')),
    path('admin/', admin.site.urls),
]

apps/aluno/urls.py
from django.urls import path

from apps.aluno.views import CadastrarAluno

urlpatterns = [
    path('new/', CadastrarAluno.as_view(), name="create-aluno"),

]

apps/home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home
urlpatterns = [
    path('', home, name='page-home'),
]

apps/professor/urls.py
from django.urls import path

from apps.professor.views import CadastrarProfessor

urlpatterns = [
    path('new/', CadastrarProfessor.as_view(), name="create-professor"),

]

apps/questao/urls.py
from django.urls import path

from apps.questao.views import CadastrarQuestao

urlpatterns = [
    path('new/', CadastrarQuestao.as_view(), name="create-questao"),

]

apps/turma/urls.py
from django.urls import path, include
from .views import CadastrarTurma
urlpatterns = [
    path('new/', CadastrarTurma.as_view(), name="create-turma"),

]

apps/aluno/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Pessoa(models.Model):

    cpf = models.CharField(max_length=15, null=False)
    nome = models.CharField(max_length=100, null=False)
    email = models.CharField(max_length=100, null=False)
    data_nascimento = models.DateField(null=False)
    rua = models.CharField(max_length=30, null=True)
    bairro = models.CharField(max_length=30, null=True)
    cidade = models.CharField(max_length=40, null=True)
    estado_uf = models.CharField(max_length=2, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Aluno(Pessoa):

    def __str__(self):
        return "Aluno: " + self.nome


    def get_absolute_url(self):
        return reverse('page-home')

apps/home/models.py
from django.db import models

# Create your models here.

apps/instituicao/models.py
from django.db import models

# Create your models here.


class Instituicao(models.Model):
    # O CODIGO É A PROPRIA PK
    nome = models.CharField(max_length=100, null=False)
    cnpj = models.CharField(max_length=18, null=False)
    rua = models.CharField(max_length=30, null=False)
    bairro = models.CharField(max_length=30, null=False)
    cidade = models.CharField(max_length=40, null=False)
    estado_uf = models.CharField(max_length=2, null=False)

    def __str__(self):
        return "Instituição: " + self.nome

apps/professor/models.py
from django.db import models
from django.urls import reverse

from apps.aluno import models


class Professor(models.Pessoa):

    def __str__(self):
        return "Professor: " + self.nome


    def get_absolute_url(self):
        return reverse('page-home')

apps/questao/models.py
from django.db import models

# Create your models here.

class Questao(models.Model):
    enunciado_questao = models.CharField(max_length=500, null=False)
    nivel = models.CharField(max_length=10, null=False)


class Alternativa(models.Model):
    enunciado_alternativa = models.CharField(max_length=500, null=False)
    alternativa_certa = models.BooleanField()
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)

    def criarAlternativa(self, pk_questao):
        pass

apps/turma/models.py
from django.db import models

# Create your models here.
from apps.professor.models import Professor


class Turma(models.Model):
    # O CODIGO É A PROPRIA PK
    periodo = models.CharField(max_length=1, null=False)
    quanttidade_alunos = models.CharField(max_length=3, null=False)
    turno = models.CharField(max_length=20, null=False)
    professores = models.ManyToManyField(Professor, blank=False)

apps/aluno/views.py
from django.contrib.auth.models import User
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView

from apps.aluno.models import Aluno


class CadastrarAluno(CreateView):
    model = Aluno
    fields = ['cpf', 'nome', 'email', 'data_nascimento', 'rua', 'bairro',
              'cidade', 'estado_uf']

    def form_valid(self, form):
        aluno = form.save(commit=False)
        username = aluno.email
        aluno.user = User.objects.create_user(username=username, password='ifrn2018')
        aluno.save()
        return super(CadastrarAluno, self).form_valid(form)

apps/home/views.py
from django.shortcuts import render

# Create your views here.



def home(request):
    return render(request, 'home/index.html')

apps/instituicao/views.py
from django.shortcuts import render

# Create your views here.

apps/professor/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic import CreateView
from apps.professor.models import Professor


class CadastrarProfessor(CreateView):
    model = Professor
    fields = ['cpf', 'nome', 'email', 'data_nascimento', 'rua', 'bairro',
              'cidade', 'estado_uf']

    def form_valid(self, form):
        professor = form.save(commit=False)
        username = professor.email
        professor.user = User.objects.create_user(username=username, password='ifrn2018')
        professor.save()
        return super(CadastrarProfessor, self).form_valid(form)

apps/questao/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView

from apps.questao.models import Questao, Alternativa


class CadastrarQuestao(CreateView):
    model = Questao
    fields = ['enunciado_questao', 'nivel']

    def form_valid(self, form):
        questao = form.save(commit=False)
        codigo = questao.pk
        Alternativa.criarAlternativa()

apps/turma/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView

from .models import Turma


class CadastrarTurma(CreateView):
    model = Turma
    fields = ['periodo', 'quanttidade_alunos', 'turno', 'professores']

apps/aluno/templates/aluno/aluno_form.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <h1>Cadastro de Aluno</h1>
    <br>
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="cpf" id="id_cpf" required>
                            <label for="id_cpf">CPF</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="data_nascimento" id="id_data_nascimento" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_data_nascimento">Dt Nascimento</label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-row">
                     <div class="form-group col-md-6">
                        <div class="group">
                            <input type="text" name="nome" id="id_nome" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_nome">Nome</label>
                        </div>
                    </div>
                     <div class="form-group col-md-6">
                        <div class="group">
                            <input type="text" name="email" id="id_email" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_email">E-mail</label>
                        </div>
                    </div>
                </div>
            </div>




            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="rua" id="id_rua" required>
                            <label for="id_rua">Rua</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="bairro" id="id_bairro" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_nome">Bairro</label>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="cidade" id="id_cidade" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_cidade">Cidade</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="estado_uf" id="id_estado_uf" required>
                            <label for="id_estado_uf">UF</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Cadastrar</button>
    </form>
{% endblock %}

apps/home/templates/home/index.html
{% extends 'base.html' %}

{% block main %}

{% endblock%}

apps/professor/templates/professor/professor_form.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <h1>Cadastro de Professor</h1>
    <br>
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="cpf" id="id_cpf" required>
                            <label for="id_cpf">CPF</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="data_nascimento" id="id_data_nascimento" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_data_nascimento">Dt Nascimento</label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-row">
                     <div class="form-group col-md-6">
                        <div class="group">
                            <input type="text" name="nome" id="id_nome" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_nome">Nome</label>
                        </div>
                    </div>
                     <div class="form-group col-md-6">
                        <div class="group">
                            <input type="text" name="email" id="id_email" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_email">E-mail</label>
                        </div>
                    </div>
                </div>
            </div>




            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="rua" id="id_rua" required>
                            <label for="id_rua">Rua</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="bairro" id="id_bairro" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_nome">Bairro</label>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="cidade" id="id_cidade" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_cidade">Cidade</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="estado_uf" id="id_estado_uf" required>
                            <label for="id_estado_uf">UF</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Cadastrar</button>
    </form>
{% endblock %}

apps/questao/templates/questao/questao_form.html
{% extends 'base.html' %}

{% block main%}
<h1>Cadastrar Questão</h1>
 {% csrf_token %}
    <form action="">
        <div class="row">
            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="enunciado_questao" id="id_enunciado_questao" required>
                            <label for="id_enunciado_questao">Enunciado</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="nivel" id="id_nivel" required>
                            <label for="id_nivel">Nivel</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Cadastrar</button>
    </form>

{% endblock %}

apps/turma/templates/turma/turma_form.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <h1>Cadastro de Turma</h1>
    <br>
    <form action="">
        <div class="row">
            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="periodo" id="id_periodo" required>
                            <label for="id_periodo">Periodo</label>
                            <span class="highlight"></span>
							<span class="bar"></span>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="turno" id="id_turno" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_turno">Turno</label>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="group">
                            <input type="text" name="quanttidade_alunos" id="id_quanttidade_alunos" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_quanttidade_alunos">Quantidade Alunos:</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <div class="group">
                            <input type="text" name="professores" id="id_professores" required>
                            <span class="highlight"></span>
							<span class="bar"></span>
                            <label for="id_professores">Professores</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Cadastrar</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% include "cabecalho_head.html" %}
    <title>Document</title>
</head>
<body>
    <header id="cabecalho">
    <div class="conteudo">

      <div id="logo" > <!-- class="pull-left" -->
        <h1><a href="{% url 'page-home'%}">SUGAA</a></h1>
        <!--  class="scrollto" -->
      </div>

      <div class="form-inline">

        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">

      </div>

      <nav> <!-- id="nav-menu-container" -->
        <ul class="nav-menu"> <!-- -->
          <li class="menu-active"><a href="{% url 'page-home'%}">Início</a></li>
          <li><a href="{% url 'create-turma'%}">Cadastrar Turma</a></li>
          <li><a href="{% url 'create-professor'%}">Cadastrar Professor</a></li>
          <li><a href="{% url 'create-aluno'%}">Cadastrar Aluno</a></li>
          
          <li class="menu-has-children"><a href="">Cadastrar Questões</a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
              <li><a href="#">Drop Down 5</a></li>
            </ul>
          </li>
           <li class="menu-has-children"><a href="">Sobre</a></li>
          <!-- <li><a href="">Contact</a></li> -->
        </ul>
      </nav><!-- #nav-menu-container -->

    </div>
  </header>

<div class="container">
    {% block main %}
    {% endblock%}
</div>
</body>
</html>

templates/cabecalho_head.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static '/css/animation.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
<script type="text/javascript" src="{% static '/js/function.js' %}"> </script>